### ISSUE TITLE
Ubuntu startup

### ISSUE THREAD

**Issue by ilyachase** [Kir-Antipov/outline-cli#10]
After default installation on Ubuntu, it appears that the VPN connects on startup. I didn't notice any configuration regarding that in the installation script.
1. Where can I find and disable the startup VPN connection?
2. Does it make sense to make it configurable in the CLI itself?

**Comment by Kir-Antipov** [comment]
Hi! `outline-cli` is configured to restore its state whenever your network status changes *(that also includes reboots)*. This means that if you were connected to the VPN, then yup, it will reconnect you. If not, it won't take any action

**Comment by ilya-levin-lokalise** [comment]
So basically I need to disconnect before rebooting and that will do it. Got it, thanks 👍

**Comment by ilyachase** [comment]
So basically I need to disconnect before rebooting and that will do it. Got it, thanks 👍
