### ISSUE TITLE
Breaks other VPN connections

### ISSUE THREAD

**Issue by inmativ** [Kir-Antipov/outline-cli#11]
After installation my organization's VPN stopped working. Please tell me where the breakdown could have occurred? Removal didn't help.

**Comment by inmativ** [comment]
As it turned out, the problem was in the modified /etc/resolv.conf file. I removed it as suggested in [this article](https://askubuntu.com/questions/1464051/how-can-i-force-ubuntu-22-04-server-to-use-only-the-dns-servers-listed-in-etc-s). And replaced it with a symlink of the file /run/systemd/resolve/stub-resolv.conf. Everything worked.

**Comment by Kir-Antipov** [comment]
Two different types of VPNs should not be used simultaneously. You need to ensure that only one VPN is active at any given time. Other than that, there should be no issues. For instance, I have both Outline and OpenVPN configured on my machine, and they coexist pretty peacefully. 

> As it turned out, the problem was in the modified /etc/resolv.conf file.

`outline-cli` temporarily modifies `resolv.conf`. However, if disabled gracefully, it should restore the file to its original state.
