### ISSUE TITLE
No support for ssconf

### ISSUE THREAD

**Issue by atolstoy** [Kir-Antipov/outline-cli#2]
Currently it s not possible to manage dynamic SS configurations (ssconf://xxx). Do you have any plans to support those?

**Comment by Kir-Antipov** [comment]
Apologies for the late reply, I'm a bit overworked at the moment :)

I'm not sure if the baseline CLI supports it *(I think it does, as it should be implemented at the SDK level)*, but if it does, then I'll add support for it here as well for sure, as it's just a matter of tweaking a few lines here and there!
