### ISSUE TITLE
[Feature request] Add support for Base64-encoded configs

### ISSUE THREAD

**Issue by jeffangelion** [Kir-Antipov/outline-cli#5]
## Examples:

```
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTptcENWdGJ5ZTVnd3ozNTJTdjViSDRaWmZ0R0xoNVRBNmJzS0w0Q1RiWjVyb1c1dzF4eFMzM1Y5UjJMdFA1VVgzc0Z2YlBpS3VXZkYzM3g4eDhndDJVM3A5RjZrNHVMcnJANDIuNDIuNDIuNDI6NTY3ODkK#Geneva+%D0%96%D0%B5%D0%BD%D0%B5%D0%B2%D0%B0
↓
1 Geneva+Женева 42.42.42.42:56789
```

```
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTptcENWdGJ5ZTVnd3ozNTJTdjViSDRaWmZ0R0xoNVRBNmJzS0w0Q1RiWjVyb1c1dzF4eFMzM1Y5UjJMdFA1VVgzc0Z2YlBpS3VXZkYzM3g4eDhndDJVM3A5RjZrNHVMcnJAc3ViZG9tYWluLmV4YW1wbGUuY29tOjU2Nzg5Cg==#Geneva+%D0%96%D0%B5%D0%BD%D0%B5%D0%B2%D0%B0
↓
1 Geneva+Женева subdomain.example.com:56789
```

## Caveats:
1. Such configs often contains algos using at server, i.e. `chacha20-ietf-poly1305`
2. Outline app importing URL-encoded config name (all after `#`) without changing `+` to space

**Comment by Kir-Antipov** [comment]
This is the first time I've seen this format. Where did it come from?

The "traditional" key format is:

```csharp
$"ss://{Base64($"{algorithm}:{password}")}@{server}:{server_port}"
```

The one you suggested is almost the same, except now everything is base64-encoded:

```csharp
$"ss://{Base64($"{algorithm}:{password}@{server}:{server_port}")}"
```

I guess these could be differentiated by the missing/present "@" symbol?

Additionally, you seem to suggest using the fragment identifier as the default name for the key when one is not specified by the user. Is that correct?

**Comment by jeffangelion** [comment]
> This is the first time I've seen this format. Where did it come from?

This key format from server provided by VPN Generator, classic Outline app handles it fine

> Additionally, you seem to suggest using the fragment identifier as the default name for the key when one is not specified by the user. Is that correct?

Well, classic Outline app also handles it, so yeah, I do suggest it
