### ISSUE TITLE
The network connection goes down when attempting to connect to a server

### ISSUE THREAD

**Issue by IvanHunters** [Kir-Antipov/outline-cli#7]

**Comment by Kir-Antipov** [comment]
Hi there! So, the main purpose of `outline-cli` is to reroute all or most of your traffic; however, if something goes wrong *(e.g., the access key you provided is invalid, the server you're trying to connect to is down, etc.)*, your traffic may effectively be sent to a black hole with no particular destination in mind. The CLI doesn't sugarcoat its users like a graphical app would do, so this behavior is somewhat expected-ish at the moment :D

You can check the logs using `tail -f /var/log/outline` to hopefully see what might have gone wrong. A healthy output should look like this:

```
OutlineVPN CLI (experimental)
[INFO] 2024/08/22 12:21:15 updated system DNS resolver: 9.9.9.9
[INFO] 2024/08/22 12:21:15 updated global IPv6 support: false
[INFO] 2024/08/22 12:21:15 remote server supports UDP, we will delegate all UDP packets to it
[INFO] 2024/08/22 12:21:15 routing traffic from 10.233.233.1 to 10.233.233.2/32 through nic 99
[INFO] 2024/08/22 12:21:15 routing traffic via gw 10.233.233.2 through nic 99...
[INFO] 2024/08/22 12:21:15 ip rule 'from all not to 42.42.42.42/32 via table 233' created
```

**Comment by maxixcom** [comment]
The same problem is here. After enabling vpn all inbound connections to the server are unavailable.
